# Generated by Django 3.1 on 2022-03-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garpix_notify', '0002_auto_20220320_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notify',
            name='event',
            field=models.IntegerField(blank=True, choices=[(1, 'Обратная связь')], null=True, verbose_name='Событие'),
        ),
        migrations.AlterField(
            model_name='notifytemplate',
            name='event',
            field=models.IntegerField(blank=True, choices=[(1, 'Обратная связь')], null=True, verbose_name='Событие'),
        ),
    ]
