# Generated by Django 3.1 on 2022-03-17 11:05

from django.db import migrations, models
import garpix_utils.file.file_field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MySetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to=garpix_utils.file.file_field.get_file_path, verbose_name='Изображение')),
                ('document', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name': 'Основная информация',
            },
        ),
    ]
